kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "spire-agent"
  labels:
    app.kubernetes.io/name: "agent"
    app.kubernetes.io/instance: "spire"
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/managed-by: "zero-trust-workload-identity-manager"
    app.kubernetes.io/part-of: "zero-trust-workload-identity-manager"
subjects:
  - kind: ServiceAccount
    name: "spire-agent"
    namespace: "zero-trust-workload-identity-manager"
roleRef:
  kind: ClusterRole
  name: "spire-agent"
  apiGroup: rbac.authorization.k8s.io
