---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - spiffecsidriverconfigs
  - spireagentconfigs
  - spireoidcdiscoveryproviderconfigs
  - spireserverconfigs
  - zerotrustworkloadidentitymanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - spiffecsidriverconfigs/finalizers
  - spireagentconfigs/finalizers
  - spireoidcdiscoveryproviderconfigs/finalizers
  - spireserverconfigs/finalizers
  - zerotrustworkloadidentitymanagers/finalizers
  verbs:
  - update
- apiGroups:
  - operator.openshift.io
  resources:
  - spiffecsidriverconfigs/status
  - spireagentconfigs/status
  - spireoidcdiscoveryproviderconfigs/status
  - spireserverconfigs/status
  - zerotrustworkloadidentitymanagers/status
  verbs:
  - get
  - patch
  - update
