---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - namespaces
  - nodes
  - nodes/proxy
  - pods
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - spiffecsidriverconfigs
  - spireagentconfigs
  - spireoidcdiscoveryproviderconfigs
  - spireserverconfigs
  - zerotrustworkloadidentitymanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - spiffecsidriverconfigs/finalizers
  - spireagentconfigs/finalizers
  - spireoidcdiscoveryproviderconfigs/finalizers
  - spireserverconfigs/finalizers
  - zerotrustworkloadidentitymanagers/finalizers
  verbs:
  - update
- apiGroups:
  - operator.openshift.io
  resources:
  - spiffecsidriverconfigs/status
  - spireagentconfigs/status
  - spireoidcdiscoveryproviderconfigs/status
  - spireserverconfigs/status
  - zerotrustworkloadidentitymanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spire.spiffe.io
  resources:
  - clusterfederatedtrustdomains
  - clusterfederatedtrustdomains/finalizers
  - clusterfederatedtrustdomains/status
  - clusterspiffeids
  - clusterspiffeids/finalizers
  - clusterspiffeids/status
  - clusterstaticentries
  - clusterstaticentries/finalizers
  - clusterstaticentries/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
