//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CASubject) DeepCopyInto(out *CASubject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CASubject.
func (in *CASubject) DeepCopy() *CASubject {
	if in == nil {
		return nil
	}
	out := new(CASubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerACMEConfig) DeepCopyInto(out *CertManagerACMEConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerACMEConfig.
func (in *CertManagerACMEConfig) DeepCopy() *CertManagerACMEConfig {
	if in == nil {
		return nil
	}
	out := new(CertManagerACMEConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerCertificateConfig) DeepCopyInto(out *CertManagerCertificateConfig) {
	*out = *in
	if in.DNSNames != nil {
		in, out := &in.DNSNames, &out.DNSNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IssuerRef != nil {
		in, out := &in.IssuerRef, &out.IssuerRef
		*out = new(CertManagerIssuerRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerCertificateConfig.
func (in *CertManagerCertificateConfig) DeepCopy() *CertManagerCertificateConfig {
	if in == nil {
		return nil
	}
	out := new(CertManagerCertificateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerIssuerConfig) DeepCopyInto(out *CertManagerIssuerConfig) {
	*out = *in
	if in.ACME != nil {
		in, out := &in.ACME, &out.ACME
		*out = new(CertManagerACMEConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerIssuerConfig.
func (in *CertManagerIssuerConfig) DeepCopy() *CertManagerIssuerConfig {
	if in == nil {
		return nil
	}
	out := new(CertManagerIssuerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerIssuerRef) DeepCopyInto(out *CertManagerIssuerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerIssuerRef.
func (in *CertManagerIssuerRef) DeepCopy() *CertManagerIssuerRef {
	if in == nil {
		return nil
	}
	out := new(CertManagerIssuerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerTLSConfig) DeepCopyInto(out *CertManagerTLSConfig) {
	*out = *in
	if in.Issuer != nil {
		in, out := &in.Issuer, &out.Issuer
		*out = new(CertManagerIssuerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(CertManagerCertificateConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerTLSConfig.
func (in *CertManagerTLSConfig) DeepCopy() *CertManagerTLSConfig {
	if in == nil {
		return nil
	}
	out := new(CertManagerTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionalStatus) DeepCopyInto(out *ConditionalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionalStatus.
func (in *ConditionalStatus) DeepCopy() *ConditionalStatus {
	if in == nil {
		return nil
	}
	out := new(ConditionalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalSecretTLSConfig) DeepCopyInto(out *ExternalSecretTLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalSecretTLSConfig.
func (in *ExternalSecretTLSConfig) DeepCopy() *ExternalSecretTLSConfig {
	if in == nil {
		return nil
	}
	out := new(ExternalSecretTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAttestor) DeepCopyInto(out *NodeAttestor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAttestor.
func (in *NodeAttestor) DeepCopy() *NodeAttestor {
	if in == nil {
		return nil
	}
	out := new(NodeAttestor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Persistence) DeepCopyInto(out *Persistence) {
	*out = *in
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Persistence.
func (in *Persistence) DeepCopy() *Persistence {
	if in == nil {
		return nil
	}
	out := new(Persistence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLExternalSecret) DeepCopyInto(out *SQLExternalSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLExternalSecret.
func (in *SQLExternalSecret) DeepCopy() *SQLExternalSecret {
	if in == nil {
		return nil
	}
	out := new(SQLExternalSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLReadOnlyConfig) DeepCopyInto(out *SQLReadOnlyConfig) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.ExternalSecret = in.ExternalSecret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLReadOnlyConfig.
func (in *SQLReadOnlyConfig) DeepCopy() *SQLReadOnlyConfig {
	if in == nil {
		return nil
	}
	out := new(SQLReadOnlyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpiffeCSIDriverConfig) DeepCopyInto(out *SpiffeCSIDriverConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpiffeCSIDriverConfig.
func (in *SpiffeCSIDriverConfig) DeepCopy() *SpiffeCSIDriverConfig {
	if in == nil {
		return nil
	}
	out := new(SpiffeCSIDriverConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpiffeOIDCProviderConfig) DeepCopyInto(out *SpiffeOIDCProviderConfig) {
	*out = *in
	if in.SpireOidcTlsConfig != nil {
		in, out := &in.SpireOidcTlsConfig, &out.SpireOidcTlsConfig
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpiffeOIDCProviderConfig.
func (in *SpiffeOIDCProviderConfig) DeepCopy() *SpiffeOIDCProviderConfig {
	if in == nil {
		return nil
	}
	out := new(SpiffeOIDCProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireAgentConfig) DeepCopyInto(out *SpireAgentConfig) {
	*out = *in
	if in.NodeAttestor != nil {
		in, out := &in.NodeAttestor, &out.NodeAttestor
		*out = new(NodeAttestor)
		**out = **in
	}
	if in.WorkloadAttestors != nil {
		in, out := &in.WorkloadAttestors, &out.WorkloadAttestors
		*out = new(WorkloadAttestors)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireAgentConfig.
func (in *SpireAgentConfig) DeepCopy() *SpireAgentConfig {
	if in == nil {
		return nil
	}
	out := new(SpireAgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireConfig) DeepCopyInto(out *SpireConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireConfig.
func (in *SpireConfig) DeepCopy() *SpireConfig {
	if in == nil {
		return nil
	}
	out := new(SpireConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpireConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireConfigLists) DeepCopyInto(out *SpireConfigLists) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpireConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireConfigLists.
func (in *SpireConfigLists) DeepCopy() *SpireConfigLists {
	if in == nil {
		return nil
	}
	out := new(SpireConfigLists)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpireConfigLists) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireConfigSpec) DeepCopyInto(out *SpireConfigSpec) {
	*out = *in
	if in.SpireServerConfig != nil {
		in, out := &in.SpireServerConfig, &out.SpireServerConfig
		*out = new(SpireServerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SpireAgentConfig != nil {
		in, out := &in.SpireAgentConfig, &out.SpireAgentConfig
		*out = new(SpireAgentConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SpiffeOIDCProviderConfig != nil {
		in, out := &in.SpiffeOIDCProviderConfig, &out.SpiffeOIDCProviderConfig
		*out = new(SpiffeOIDCProviderConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SpiffeCSIDriverConfig != nil {
		in, out := &in.SpiffeCSIDriverConfig, &out.SpiffeCSIDriverConfig
		*out = new(SpiffeCSIDriverConfig)
		**out = **in
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]*corev1.Toleration, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1.Toleration)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireConfigSpec.
func (in *SpireConfigSpec) DeepCopy() *SpireConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SpireConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireConfigStatus) DeepCopyInto(out *SpireConfigStatus) {
	*out = *in
	in.ConditionalStatus.DeepCopyInto(&out.ConditionalStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireConfigStatus.
func (in *SpireConfigStatus) DeepCopy() *SpireConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SpireConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireSQLConfig) DeepCopyInto(out *SpireSQLConfig) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExternalSecret != nil {
		in, out := &in.ExternalSecret, &out.ExternalSecret
		*out = new(SQLExternalSecret)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(SQLReadOnlyConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireSQLConfig.
func (in *SpireSQLConfig) DeepCopy() *SpireSQLConfig {
	if in == nil {
		return nil
	}
	out := new(SpireSQLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireServerConfig) DeepCopyInto(out *SpireServerConfig) {
	*out = *in
	if in.SpireServerKeyManager != nil {
		in, out := &in.SpireServerKeyManager, &out.SpireServerKeyManager
		*out = new(SpireServerKeyManager)
		**out = **in
	}
	if in.CASubject != nil {
		in, out := &in.CASubject, &out.CASubject
		*out = new(CASubject)
		**out = **in
	}
	if in.SpireServerResources != nil {
		in, out := &in.SpireServerResources, &out.SpireServerResources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(Persistence)
		(*in).DeepCopyInto(*out)
	}
	if in.SpireSQLConfig != nil {
		in, out := &in.SpireSQLConfig, &out.SpireSQLConfig
		*out = new(SpireSQLConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireServerConfig.
func (in *SpireServerConfig) DeepCopy() *SpireServerConfig {
	if in == nil {
		return nil
	}
	out := new(SpireServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireServerKeyManager) DeepCopyInto(out *SpireServerKeyManager) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireServerKeyManager.
func (in *SpireServerKeyManager) DeepCopy() *SpireServerKeyManager {
	if in == nil {
		return nil
	}
	out := new(SpireServerKeyManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.ExternalSecret != nil {
		in, out := &in.ExternalSecret, &out.ExternalSecret
		*out = new(ExternalSecretTLSConfig)
		**out = **in
	}
	if in.CertManager != nil {
		in, out := &in.CertManager, &out.CertManager
		*out = new(CertManagerTLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadAttestors) DeepCopyInto(out *WorkloadAttestors) {
	*out = *in
	if in.WorkloadAttestorsVerification != nil {
		in, out := &in.WorkloadAttestorsVerification, &out.WorkloadAttestorsVerification
		*out = new(WorkloadAttestorsVerification)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadAttestors.
func (in *WorkloadAttestors) DeepCopy() *WorkloadAttestors {
	if in == nil {
		return nil
	}
	out := new(WorkloadAttestors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadAttestorsVerification) DeepCopyInto(out *WorkloadAttestorsVerification) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadAttestorsVerification.
func (in *WorkloadAttestorsVerification) DeepCopy() *WorkloadAttestorsVerification {
	if in == nil {
		return nil
	}
	out := new(WorkloadAttestorsVerification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroTrustWorkloadIdentityManager) DeepCopyInto(out *ZeroTrustWorkloadIdentityManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroTrustWorkloadIdentityManager.
func (in *ZeroTrustWorkloadIdentityManager) DeepCopy() *ZeroTrustWorkloadIdentityManager {
	if in == nil {
		return nil
	}
	out := new(ZeroTrustWorkloadIdentityManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZeroTrustWorkloadIdentityManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroTrustWorkloadIdentityManagerList) DeepCopyInto(out *ZeroTrustWorkloadIdentityManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZeroTrustWorkloadIdentityManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroTrustWorkloadIdentityManagerList.
func (in *ZeroTrustWorkloadIdentityManagerList) DeepCopy() *ZeroTrustWorkloadIdentityManagerList {
	if in == nil {
		return nil
	}
	out := new(ZeroTrustWorkloadIdentityManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZeroTrustWorkloadIdentityManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroTrustWorkloadIdentityManagerSpec) DeepCopyInto(out *ZeroTrustWorkloadIdentityManagerSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]*corev1.Toleration, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1.Toleration)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroTrustWorkloadIdentityManagerSpec.
func (in *ZeroTrustWorkloadIdentityManagerSpec) DeepCopy() *ZeroTrustWorkloadIdentityManagerSpec {
	if in == nil {
		return nil
	}
	out := new(ZeroTrustWorkloadIdentityManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroTrustWorkloadIdentityManagerStatus) DeepCopyInto(out *ZeroTrustWorkloadIdentityManagerStatus) {
	*out = *in
	in.ConditionalStatus.DeepCopyInto(&out.ConditionalStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroTrustWorkloadIdentityManagerStatus.
func (in *ZeroTrustWorkloadIdentityManagerStatus) DeepCopy() *ZeroTrustWorkloadIdentityManagerStatus {
	if in == nil {
		return nil
	}
	out := new(ZeroTrustWorkloadIdentityManagerStatus)
	in.DeepCopyInto(out)
	return out
}
